
## WorkFlow Name.
name: Unit Tests.

## Actions that will be executed when you push code currently none
on:
  push:
    branches: [ main , dev ]
  pull_request:
    branches: [ main , dev ]


## Jobs to be executed.
jobs:
  ## Run unit test.
  unit_tests:
    name: Run Unit Tests.
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      ## Run unit tests.
      - name: Unit tests
        run: ./gradlew testDebugUnitTest


  publish_test_report:
    name: Generate Testing Report.
    runs-on: [ubuntu-latest]
    needs:
      - unit_tests
    steps:
      - uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-result/testDebugUnitTest/TEST-com.ameen.expirydatetracker.util.UtilsTest.xml