
## WorkFlow Name.
name: Unit Tests.

## Actions that will be executed when you push code currently none
on:
  push:
    branches: [ main , dev ]
  pull_request:
    branches: [ main , dev ]


## Jobs to be executed.
jobs:
  ## Run unit test.
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      steps:
        - uses: actions/checkout@v1
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Unit tests
          run: bash ./gradlew test --stacktrace